# Generated by Django 5.0.1 on 2024-02-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedCPF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_birth", models.DateField()),
                ("generated_cpf", models.CharField(max_length=11)),
            ],
        ),
    ]
